backports.gemspec
This is just a simple tweak to include the license when building the Gem. I took a look at the LICENSE.txt file and it appeared to be the MIT license, so that is what I put into the .gemspec.
=> Indicate MIT license in .gemspec

README.rdoc
I tried requiring the `Random` class this way in 1.8.7 and it had no effect. Using the other require path worked, however.
=> Remove potentially erroneous import comment

lib/backports/2.4.0/string.rb
Before:
```
2.3.5 :001 > require 'backports/2.4.0'
=> true 
2.3.5 :002 > 'a'.match?(/a/)
NoMethodError: undefined method `match?' for "a":String
Did you mean?  match
from (irb):2
```
After:
```
2.3.5 :002 > require 'backports/2.4.0'
=> true 
2.3.5 :003 > 'a'.match?(/a/)
=> true 
````
=> add missing string.rb for recursive require of 2.4 features

lib/backports.rb
The documentation says:
> For example, any version of Ruby up to today's standards:
`require 'backports'`
This makes that true again, since currently it misses all of the 2.2/2.3/2.4 features by default.
=> update the all require to start with 2.4 features

lib/backports/2.5.0/dir/children.rb, lib/backports/2.5.0/dir/each_child.rb, lib/backports/2.5.0/struct/new.rb
Before:
```ruby
$ irb -rbackports/latest
/home/zverok/.rvm/gems/ruby-2.3.3/gems/backports-3.11.0/lib/backports/2.5.0/dir/each_child.rb:2: warning: already initialized constant Backports::EXCLUDED_CHILDREN
/home/zverok/.rvm/gems/ruby-2.3.3/gems/backports-3.11.0/lib/backports/2.5.0/dir/children.rb:2: warning: previous definition of EXCLUDED_CHILDREN was here
asdasd
2.3.3 :001 > 
```
After:
```ruby
$ irb -rbackports/latest
2.3.3 :001 > 
```
(`asdasd` was a nice touch, should I say)
I am not sure whether the const duplication should be solved in a smarter way, though.
=> Avoid warnings for Dir backports

backports.gemspec
Add metadata links for quick access from the rubygems catalogue.
=> Add rubygems metadata

Rakefile
This makes things like `rake spec[array/to_h]` not output a confusing "No spec found for array/to_h".
Note, for super-old versions of ruby, the message will still happen because they are not tested against the up to date spec.
=> Avoid displaying "No spec found for" because of old spec

default.mspec, test/_backport_guards_test.rb
Solves problems when running tests on patch version of ruby, ex 2.2.7 instead of 2.2.0.
=> Fix tests in patch versions of Ruby

lib/backports/1.9.1/string/codepoints.rb
In Ruby 1.9.1 `codepoints` returns an enumerator when no block is given:
```ruby
'ABC'.codepoints
#=> #<Enumerator: "ABC":codepoints>
```
The backports version does the same.
If however a block is given, the native implementation returns the receiver, making it chainable:
```ruby
'ABC'.codepoints {}
#=> "ABC"
```
whereas the backports version returns the codepoints:
```ruby
'ABC'.codepoints {}
#=> [65, 66, 67]
```
This commit fixes the return value by returning `self`.
=> Fix return value for String#codepoints

README.rdoc, lib/backports/2.6.0/method.rb, lib/backports/2.6.0/method/compose.rb, lib/backports/2.6.0/proc.rb, lib/backports/2.6.0/proc/compose.rb
This adds the Ruby 2.6 function composition methods #<< and #>>. The code came from https://www.ghostcassette.com/function-composition-in-ruby/
=> Proc/Method #<< and #>> composition methods

lib/backports/version.rb
Currently, the use of Mixins might trigger wrong setting of version information.
See example below.
```
module Test
VERSION = "1.0.0"
end
include Test
require 'backports'
Backports::VERSION
NameError (uninitialized constant Backports::VERSION)
Did you mean?  VERSION
```
=> Fix version guard

.rubocop.yml, Gemfile, Rakefile, lib/backports/2.2.0/enumerable/slice_after.rb, lib/backports/2.2.0/float/next_float.rb, lib/backports/2.2.0/float/prev_float.rb, lib/backports/2.2.0/method/super_method.rb, lib/backports/2.3.0/array/bsearch_index.rb, lib/backports/2.3.0/hash/lt.rb, lib/backports/2.3.0/hash/lte.rb, lib/backports/2.3.0/hash/to_proc.rb, lib/backports/2.3.0/struct/dig.rb, lib/backports/2.4.0/hash/transform_values.rb, lib/backports/2.4.0/true_class/dup.rb, lib/backports/2.5.0/hash/transform_keys.rb, lib/backports/2.5.0/integer/sqrt.rb, lib/backports/2.5.0/module/alias_method.rb, lib/backports/2.5.0/string/undump.rb, lib/backports/2.5.0/struct/new.rb, lib/backports/2.6.0/enumerable/chain.rb, lib/backports/2.6.0/hash/to_h.rb, lib/backports/2.7.0/enumerable/filter_map.rb
This PR is an attempt to introduce Rubocop to backports codebase.
The main goal is to make future backports easier to develop.
Some decisions made in this PR (I am ready to amend any of them):
* Old files (for Rubies before 2.1) are excluded from the check; they represent all kinds of old styles, and as they will probably never change (and will probably be dropped in v.3), there is no point either in fixing them or in trying to produce Rubocop's config that suits all styles seen in the codebase;
* Metrics (complexity, module/method length) and Naming (parameter and file names) are excluded completely as not suitable for the situation;
* Checks that the codebase is consistent about, are turned on (with the settings corresponding to codebase's preferences); 
* Checks that codebase is not …
=> Add Rubocop

README.md
Noticed the example link the readme was broken, so fixed it (and a typo).
That's all.
=> Fix README formatting (and a typo)

lib/backports/2.0.0/range/size.rb
The full error message is:
```
NameError: uninitialized constant Float::INFINITY
/home/khiav/.rvm/gems/ruby-1.8.7-p374/gems/backports-3.16.1/lib/backports/2.0.0/range/size.rb:7:in `size'
```
=> Fix: NameError: uninitialized constant Float::INFINITY

lib/backports/2.5.0/struct/new.rb
`Kernel.eval` accepts binding as the second argument and file and line as the latter two.
Found it while trying to use with 2.4:
```sh
$ ruby -v
ruby 2.4.10p364 (2020-03-31 revision 67879) [x86_64-linux]
$ ruby -rbackports/latest -e "p :ok"
/usr/local/bundle/gems/backports-3.17.1/lib/backports/2.5.0/struct/new.rb:3:in `eval': no implicit conversion of Integer into String (TypeError)
from /usr/local/bundle/gems/backports-3.17.1/lib/backports/2.5.0/struct/new.rb:3:in `<top (required)>'
from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /usr/local/bundle/gems/backports-3.17.1/lib/backports/std_lib.rb:12:in `require_with_backports'
...
from …
```
=> Fix 2.5 Struct.new

lib/backports/1.8.7.rb, lib/backports/1.9.1.rb, lib/backports/1.9.2.rb, lib/backports/1.9.3.rb, lib/backports/2.0.0.rb, lib/backports/2.1.0.rb, lib/backports/2.2.0.rb, lib/backports/2.3.0.rb, lib/backports/2.4.0.rb, lib/backports/2.5.0.rb, lib/backports/2.6.0.rb, lib/backports/2.7.0.rb, lib/backports/tools/require_relative_dir.rb, test/_backport_guards_test.rb
Well... I am aware that you are kinda frowning upon `require 'backports/latest'`, but we are using it nevertheless. One bad thing that happening in this case, is (especially in Rails-infected project with tons of `require` redefinitions) it is quite slow.
Measured with [Bumbler](https://github.com/nevir/Bumbler), our slowest requires are:
```
....
578.10  aws-sdk-ec2
682.34  aws-sdk-s3
1117.32  backports/latest <======== :scream:
1292.85  rails
```
That's because being on 2.6, and requiring backports to have some 2.7 stuff, we in fact perform thousands of requires, which are effectively no-ops, down to some `backports/1.8.7/range/step`... I believe that reducing number of unnecessary requires is a good thing in any case.
(Not sure what CI will say about that, though...)
=> Reduce number of requires with version-based conditions

lib/backports/2.3.0/string.rb
Just found that String additions are not loaded in Ruby 2.2.
=> fix: add missing 2.3.0/string.rb

README.md, lib/backports/2.4.0/string/unpack1.rb
This implements `String#unpack1` which was added first to Ruby 2.4.0 in https://bugs.ruby-lang.org/issues/12752
=> Implement String#unpack1

README.md, lib/backports/2.7.0/symbol.rb, lib/backports/2.7.0/symbol/end_with.rb
Backport `Symbol#end_with?` (available as of Ruby 2.7.0)
=> ruby-2.7: Symbol#end_with?

lib/backports/2.7.0/symbol/end_with.rb
Fixes minor typo introduced in https://github.com/marcandre/backports/pull/171
The issue isn't noticeable as `backports/1.8.7/string/end_with` has proper guard.
=> Fix String#end_with? guard clause in Symbol

.github/workflows/backports.yml
Without quotes, the 3.0 is truncated to 3 and it loads the most recent Ruby 3 release - at this point Ruby 3.1.  Adding quotes ensures that a Ruby 3.0.x is loaded, as intended.
This can be seen in the Actions screen:
=> Quote the 3.0 to ensure it loads a 3.0.x Ruby

lib/backports/3.2.0/enumerator/product.rb
Fixes 10 cases from rubyspec:
* Size error cases
* Enumerator.product rejects kwargs by name
* Product#rewind rewinds in "direct order", not reverse
JRuby is using this impl for now, and this brings the failure count for the `Enumerator::Product` specs down to 10 (43 total, 20 failures without this PR).
=> A few small fixes for rubyspecs

lib/backports/3.2.0/enumerator/product.rb
This contains (almost) all changes made in JRuby to the backports `Enumerable#product` implementation while getting CRuby tests passing.
* Return `self` from most methods as in the C code.
* Include negative infinity in bail-out logic for `size`.
* Handle block passed to `product` by yielding all results.
* Add `initialize_copy` impl.
I also have an implementation of `inspect` but it depends on JRuby-specific recursion-detection logic:
https://github.com/jruby/jruby/blob/56d126f04589b7636098a0de4b2ae79a76dec3ae/core/src/main/ruby/jruby/kernel/enumerator.rb#L545-L557
=> Fixes for Enumerator#product from JRuby
